bucket         = "jenkins-terraform-state-production"
encrypt        = "true"
kms_key_id     = "arn:aws:kms:ap-south-1:278306660155:alias/jenkins-terraform-state-key-production"
region         = "ap-south-1"
dynamodb_table = "jenkins-terraform-state-production"
key            = "jenkins/production.tfstate"