---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.78.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-write=true
      - id: terraform_tflint
        args:
          - "--args=--config=.tflint.hcl"
      - id: terraform_tfsec
        args:
         - "--args=-e aws-ec2-add-description-to-security-group-rule,aws-ec2-no-public-ingress-sgr,aws-ec2-no-public-egress-sgr,aws-elb-alb-not-public,aws-ec2-require-vpc-flow-logs-for-all-vpcs,aws-s3-enable-bucket-encryption,aws-s3-encryption-customer-key,aws-s3-enable-bucket-logging,aws-s3-enable-versioning,aws-dynamodb-enable-at-rest-encryption,aws-dynamodb-enable-recovery,aws-dynamodb-table-customer-key"
  -   repo: local
      hooks:
      -   id: terraform_docs
          name: Generate terraform docs
          language: script
          entry: ./scripts/terraform_docs.sh