---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.78.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-write=true
      - id: terraform_tflint
        args:
          - "--args=--config=.tflint.hcl"
      - id: terraform_tfsec
  -   repo: local
      hooks:
      -   id: terraform_docs
          name: Generate terraform docs
          language: script
          entry: ./scripts/terraform_docs.sh