version: "3.8"

services:
  # Monitoring components
  nodeexporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    depends_on:
      jenkins:
        condition: service_healthy
  jenkins:
    build: .
    volumes:
      - /jenkins:/var/jenkins_home
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s