- hosts: docker
  vars:
   docker_compose_url: https://github.com/docker/compose/releases/download/v2.13.0/docker-compose-Linux-x86_64
  pre_tasks:
    - name: Install Docker Compose
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'
      become: true
  roles:
    - app/docker
  tags: docker